<?php
namespace Akamai\Services;

use Akamai\Facades\Config;
use Akamai\Exceptions\AuthTokenNotFoundException;

/**
    * class to generate the Token for Akamai Video Streaming
    *
        mandatory Fields for AkamaiToken to work
        1) ACL = /* or *
        2) Start time = unix time stamp
        3) Window = duration of which the token is valid
        4) Key = Auth Key generated by Akamai

        <URL>?hdnts=<token>
               OR
        <URL>?hdnea=<token>
*/

class TokenGenerator
{

    protected $algo = '';
    protected $ip = '';
    protected $start_time = 0;
    protected $window;
    protected $acl = '';
    protected $url = '';
    protected $session_id = '';
    protected $data = '';
    protected $salt = '';
    protected $key = '';
    protected $field_delimiter = '~';
    protected $early_url_encoding = false;
    protected $opts; // array;
    protected $config; // array;

    
    public function __CONSTRUCT($duration)
    {
        $this->config = Config::getAkamaiConfig();
        $this->setOptions($duration);
    }

    private function setOptions($duration)
    {
        if (!isset($this->config['AKAMAI_VIDEO_TOKEN']) || !trim($this->config['AKAMAI_VIDEO_TOKEN'])) {
            throw new AuthTokenNotFoundException("Akamai authentication token (AKAMAI_VIDEO_TOKEN) is not found in the loaded config", 1003);
        }

        $this->opts =  [
            'start-time=' => "now",
            'algo=' => 'sha256',
            'window=' => $duration,
            'key' => $this->config['AKAMAI_VIDEO_TOKEN'],
            'acl=' => '*',
        ];
    }

    protected function encode($val)
    {
        if ($this->early_url_encoding === true) {
            return rawurlencode($val);
        }
        return $val;
    }

    public function setAlgorithm($algo)
    {
        if (in_array($algo, array('sha256','sha1','md5'))) {
            $this->algo = $algo;
        } else {
            throw new Exception("Invalid algorithm, must be one of 'sha256', 'sha1' or 'md5'");
        }
    }

    public function getAlgorithm()
    {
        return $this->algo;
    }

    public function setUID($v)
    {
        $this->uid = (int)$v;
    }

    public function getUID()
    {
        return $this->uid;
    }

    public function setIP($ip)
    {
        // @TODO: Validate IPV4 & IPV6 addrs
        $this->ip = $ip;
    }

    public function getIP()
    {
        return $this->ip;
    }

    public function getIPField()
    {
        if ($this->ip != "") {
            return 'ip='.$this->ip.$this->field_delimiter;
        }
        return "";
    }

    public function setStartTime($start_time)
    {
        // verify starttime is sane
        if (strcasecmp($start_time, "now") == 0) {
            $this->start_time = time();
        } else {
            if (is_numeric($start_time) && $start_time > 0 && $start_time < 4294967295) {
                $this->start_time = 0+$start_time; // faster then intval
            } else {
                throw new Exception("start time input invalid or out of range");
            }
        }
    }

    public function getStartTime()
    {
        return $this->start_time;
    }

    protected function getStartTimeValue()
    {
        if ($this->start_time > 0) {
            return $this->start_time;
        } else {
            return time();
        }
    }

    public function getStartTimeField()
    {
        if (is_numeric($this->start_time) && $this->start_time > 0 && $this->start_time < 4294967295) {
            return "st=".$this->getStartTimeValue().$this->field_delimiter;
        } else {
            return '';
        }
    }

    public function setWindow($window)
    {
        // verify window is sane
        if (is_numeric($window) && $window > 0) {
            $this->window = 0+$window; // faster then intval
        } else {
            $this->throwError("window input invalid");
            
        }
    }

    public function getWindow()
    {
        return $this->window;
    }

    public function getExpriryField()
    {
        return "exp=".($this->getStartTimeValue()+$this->getWindow()).$this->field_delimiter;
    }

    public function setACL($acl)
    {
        if ($this->url != "") {
            $this->throwError("Cannot set both an ACL and a URL at the same time");

        }
        $this->acl = $acl;
    }

    public function getACL()
    {
        return $this->acl;
    }

    public function getACLField()
    {
        if ($this->acl) {
            return 'acl='.$this->encode($this->acl).$this->field_delimiter;
        } elseif (! $this->url) {
            //return a default open acl     $token = $g->generateToken($this);
            return 'acl='.$this->encode('*').$this->field_delimiter;
            //return 'acl='.$this->encode('/*').$this->field_delimiter;
        }
        return '';
    }

    public function setURL($url)
    {
        if ($this->acl) {
            $this->throwError("Cannot set both an ACL and a URL at the same time");
        }
        $this->url = $url;
    }
    public function getURL()
    {
        return $this->url;
    }
    public function getURLField()
    {
        if ($this->url && ! $this->acl) {
            return 'url='.$this->encode($this->url).$this->field_delimiter;
        }
        return '';
    }

    public function setSessionID($session_id)
    {
        $this->session_id = $session_id;
    }

    public function getSessionID()
    {
        return $this->session_id;
    }

    public function getSessionIDField()
    {
        if ($this->session_id) {
            return 'id='.$this->session_id.$this->field_delimiter;
        }
        return "";
    }

    public function setData($data)
    {
        $this->data = $data;
    }

    public function getData()
    {
        return $this->data;
    }

    public function getDataField()
    {
        if ($this->data) {
            return 'data='.$this->data.$this->field_delimiter;
        }
        return "";
    }

    public function setSalt($salt)
    {
        $this->salt = $salt;
    }

    public function getSalt()
    {
        return $this->salt;
    }

    public function getSaltField()
    {
        if ($this->salt) {
            return 'salt='.$this->salt.$this->field_delimiter;
        }
        return "";
    }

    public function setKey($key)
    {
        //verify the key is valid hex
        if (preg_match('/^[a-fA-F0-9]+$/', $key) && (strlen($key)%2) == 0) {
            $this->key = $key;
        } else {
            $this->throwError("Key must be a hex string (a-f,0-9 and even number of chars)");
        }
    }
    public function getKey()
    {
        return $this->key;
    }

    public function setFieldDelimiter($field_delimiter)
    {
        $this->field_delimiter = $field_delimiter;
    }

    public function getFieldDelimiter()
    {
        return $this->field_delimiter;
    }

    /*
    public function set_early_url_encoding($early_url_encoding) {
        $this->early_url_encoding = $early_url_encoding;
    }

    public function get_early_url_encoding() {
        return $this->early_url_encoding;
    }
    */

    
    protected function h2b($str)
    {
        $bin = "";
        $i = 0;
        do {
            $bin .= chr(hexdec($str{$i}.$str{($i + 1)}));
            $i += 2;
        } while ($i < strlen($str));
        return $bin;
    }

    private function throwError($message = '')
    {
        echo 'Error: '.$message;
    }

    // Mandatory is time
    // ACL is mandatory and IP, data and session is optional
    // ACL ="/*"

    public function generateToken()
    {
        // ASSUMES:($algo='sha256', $ip='', $start_time=null, $window=300, $acl=null, $acl_url="", $session_id="", $payload="", $salt="", $key="000000000000", $field_delimiter="~")
        try {
            $m_token = $this->getIPField();
            $m_token .= $this->getStartTimeField();
            $m_token .= $this->getExpriryField();
            $m_token .= $this->getACLField();
            
            /*
            $m_token .= $this->getSessionIDField();
            $m_token .= $this->getDataField();
            */

            $m_token_digest = (string)$m_token;
            $m_token_digest .= $this->getURLField();
            $m_token_digest .= $this->getSaltField();
            
            // produce the signature and append to the tokenized string
            $signature = hash_hmac($this->getAlgorithm(), rtrim($m_token_digest, $this->getFieldDelimiter()), $this->h2b($this->getKey()));
            return $m_token.'hmac='.$signature;
        
        } catch (Exception $e) {
            $this->throwError($e->getMessage());
        }
        
    }


    public function getToken()
    {

        if (is_array($this->opts) && !empty($this->opts)) {
            foreach ($this->opts as $o => $v) {
                    
                if (($o == 'window=') || ($o == 'w')) {
                    $this->setWindow($v);
                } elseif (($o == 'start-time=') || ($o == 's')) {
                    $this->setStartTime($v);
                } elseif (($o == 'ip=') || ($o == 'i')) {
                    $this->setIP($v);
                } elseif (($o == 'acl=') || ($o == 'a')) {
                    $this->setACL($v);
                } elseif (($o == 'session-id=') || ($o == 'I')) {
                    $this->setSessionID($v);
                } elseif (($o == 'url=') || ($o == 'u')) {
                    $this->setURL($v);
                } elseif (($o == 'salt=') || ($o == 'S')) {
                    $this->setSalt($v);
                } elseif (($o == 'field-delimiter=') || ($o == 'd')) {
                    $this->setFieldDelimiter($v);
                } elseif (($o == 'algo=') || ($o == 'A')) {
                    $this->setAlgorithm($v);
                } elseif (($o == 'key') || ($o == 'k')) {
                    $this->setKey($v);
                }
            }
        
            return  $this->generateToken();
            
        }
    }
}
